app/routes.py
"""
The `views` blueprint contains the route definitions and corresponding view functions for the application.

The routes defined in this blueprint include:
- `home()`: Renders the home page, displaying the top-level files and directories.
- `all_files(inode_id)`: Renders a page displaying all files and directories within the specified directory.
- `upload()`: Handles file uploads, adding new files to the database and file system.
- `create()`: Handles directory creation, adding new directories to the database and file system.
- `download(inode_id)`: Allows downloading of files from the file system.
- `delete(inode_id)`: Deletes files or directories from the database and file system.
- `move(source_inode_id)`: Marks an inode for moving to a new location.
- `copy(source_inode_id)`: Marks an inode for copying to a new location.
- `paste(target_parent_id)`: Moves or copies the marked inode to the specified target directory.

The blueprint also includes two helper functions, `copy_children()` and `move_children()`, which recursively handle the copying or moving of child inodes when a directory is copied or moved.
"""


from . import db
from app.models import Inode
from app.utils import allowed_file, generate_path
from werkzeug.utils import secure_filename
from flask import request, render_template, send_file, url_for, flash, redirect
import os
import shutil
from flask import Blueprint


views = Blueprint('views', __name__)

tempInodeId = 0
move_in_progress = False

@views.route('/')
def home():
    inodes = Inode.query.filter_by(parent_id=1)
    parent_inode = Inode.query.filter_by(id=1).first()
    return render_template('home.html', inodes=inodes, parent_inode=parent_inode)


@views.route('/all_files/<int:inode_id>')
def all_files(inode_id):
    inodes = Inode.query.filter_by(parent_id = inode_id)
    parent_inode = Inode.query.filter_by(id=inode_id).first()
    return render_template('all_files.html', inodes=inodes, parent_inode=parent_inode)


@views.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        # Get the file from the request
        file = request.files['file']
        pid = int(request.form['parent_id'])

        # check is file already exists
        inode = Inode.query.filter_by(name=file.filename, parent_id=pid).first()
        if inode:
            flash(f"File already exists: {file.filename}")
            return redirect(url_for('views.all_files', inode_id=pid))

        # Check if file is not none and it is allowed (filetype)...
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)

            filepath = generate_path(filename, pid)
            file.save(filepath)

        new_inode = Inode(name=filename, is_file=True, parent_id=pid, owner_id=1, path=filepath)
        db.session.add(new_inode)
        db.session.commit()

    return redirect(url_for('views.all_files', inode_id=pid))


@views.route('/create', methods=['POST'])
def create():
    if request.method == 'POST':
        dirname = request.form['dirname']
        pid = int(request.form['parent_id'])

    # check if dir already exists? if not, create new inode and add it to the database
    try:
        dirpath=generate_path(dirname, pid)
        os.mkdir(dirpath)
        new_inode = Inode(name=dirname, is_file=False, parent_id=pid, owner_id=1, path=dirpath)
        db.session.add(new_inode)
        db.session.commit()

        flash(f'Directory {dirname} created successfully!')

    except Exception as e:
        flash(f"Error: {str(e)}")
        print(e)

    return redirect(url_for('views.all_files', inode_id=pid))



@views.route('/download/<int:inode_id>')
def download(inode_id):
    inode = Inode.query.filter_by(id=inode_id).first()
    if inode.is_file:
        file_to_send = os.path.abspath(inode.path)
        return send_file(file_to_send, as_attachment=True, download_name=inode.name)
    else:
        flash('Cannot download directory!')
        return redirect(url_for('views.all_files', inode_id=inode.parent_id))



@views.route('/delete/<int:inode_id>')
def delete(inode_id):
    inode = Inode.query.filter_by(id=inode_id).first()

    # if inode is file, delete the file
    if inode.is_file:
        os.remove(inode.path)
    else:
        # removes whole directory tree
        shutil.rmtree(inode.path)

    flash(f'{inode.name} deleted successfully!')
    db.session.delete(inode)
    db.session.commit()

    return redirect(url_for('views.all_files', inode_id=inode.parent_id))


@views.route('/move/<int:source_inode_id>')
def move(source_inode_id):
    global tempInodeId, move_in_progress
    move_in_progress = True
    tempInodeId = source_inode_id
    flash('Data cut successfully!')
    return redirect(url_for('views.home'))


@views.route('/copy/<int:source_inode_id>')
def copy(source_inode_id):
    global tempInodeId, move_in_progress
    move_in_progress = False
    tempInodeId = source_inode_id
    flash('Data copied successfully')
    return redirect(url_for('views.home'))


@views.route('/paste/<int:target_parent_id>')
def paste(target_parent_id):
    global tempInodeId, move_in_progress, children_nodes_list
    children_nodes_list = []  # Reset the children_nodes_list

    tempInode = Inode.query.filter_by(id=tempInodeId).first()

    # Logic for moving inodes...
    if move_in_progress:
        try:
            new_path = generate_path(tempInode.name, target_parent_id)
            if tempInode.is_file:
                if os.path.exists(new_path):
                    flash(f"File already exists: {new_path}")
                else:
                    shutil.move(tempInode.path, new_path)
                    tempInode.path = new_path
                    tempInode.parent_id = target_parent_id
                    flash(f'{tempInode.name} moved successfully!')

            else:
                if os.path.exists(new_path):
                    flash(f"Directory already exists: {new_path}")
                else:
                    shutil.move(tempInode.path, new_path)
                    tempInode.path = new_path
                    tempInode.parent_id = target_parent_id
                    move_children(tempInode.id)

                    flash(f'{tempInode.name} moved successfully!')
            db.session.commit()
            move_in_progress = False

        except Exception as e:
            flash(f"Error: {str(e)}")
            print(e)

    # Logic for copying inodes...
    else:
        new_name = f"copy__{tempInode.name}"
        new_path = generate_path(new_name, target_parent_id)

        try:
            if tempInode.is_file:
                if os.path.exists(new_path):
                    flash(f"File already exists: {new_path}")
                else:
                    shutil.copy(tempInode.path, new_path)
                    new_inode = Inode(
                        name=new_name,
                        is_file=tempInode.is_file,
                        parent_id=target_parent_id,
                        owner_id=tempInode.owner_id,
                        path=new_path
                    )
                    db.session.add(new_inode)
                    db.session.commit()
                    flash(f'{new_inode.name} pasted successfully!')

            else:
                if os.path.exists(new_path):
                    flash(f"Directory already exists: {new_path}")
                else:
                    shutil.copytree(tempInode.path, new_path)
                    new_inode = Inode(
                        name=new_name,
                        is_file=tempInode.is_file,
                        parent_id=target_parent_id,
                        owner_id=tempInode.owner_id,
                        path=new_path
                    )
                    db.session.add(new_inode)
                    db.session.commit()
                    copy_children(tempInode.id, new_inode.id)
                    flash(f'{new_inode.name} pasted successfully!')

        except Exception as e:
            flash(f"Error: {str(e)}")
            print(e)

    return redirect(url_for('views.home'))



# Recurssive copy children function which gets all the children nodes and creates a copy of it.
def copy_children(source_parent_id, new_parent_id):
    Children_Inodes = Inode.query.filter_by(parent_id=source_parent_id).all()
    for child in Children_Inodes:

        new_inode = Inode(
            name=child.name,
            is_file=child.is_file,
            parent_id=new_parent_id,
            owner_id=child.owner_id,
            path=generate_path(child.name, new_parent_id)
        )
        db.session.add(new_inode)
        db.session.commit()
        if not child.is_file:
            copy_children(child.id, new_inode.id)


# Recurssive move children function which gets all the children and updates their path and parent id.

def move_children(parent_inode_id):
    Children_Inodes = Inode.query.filter_by(parent_id=parent_inode_id).all()
    for child in Children_Inodes:
        child.pid = parent_inode_id
        child.path = generate_path(child.name, parent_inode_id)
        if not child.is_file:
            move_children(child.id)
        db.session.commit()

app/templates/all_files.html
{% extends "base.html" %}


{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-5 mx-auto">

        <div class="flex flex-row grid grid-cols-2 gap-2 text-center w-full mb-20">

            <div class="border-2 border-slate-900 rounded-xl">

                <h3 class="font-mono">UPLOAD A FILE</h3>

                <div class="mx-auto w-full px-5 py-5">
                    <form method="post" action="/upload" enctype="multipart/form-data">


                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                            for="file_input">Select File</label>
                        <input
                            class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                            name="file" aria-describedby="file_input_help" id="file_input" type="file" required>


                        <input type="hidden" name="parent_id" value="{{ parent_inode.id }}">

                        <p class="mt-1 mx-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">ALLOWED
                            EXTENSIONS : TXT,
                            PDF,
                            PNG, JPG, JPEG, GIF, MP4, DOCX, PPTX
                        </p>

                        <input type="submit" value="Upload File"
                            class="my-5 w-full text-white bg-gray-900 hover:bg-blue-900  font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2">

                    </form>
                </div>
            </div>




            <div class="border-2 border-slate-900 rounded-xl">

                <h3 class="font-mono">CREATE NEW DIRECTORY</h3>
                <form method="post" action="/create" class="my-5 container mx-auto w-full px-4">
                    <div class="mb-3">
                        <label for="dirname"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Directory
                            Name
                            :
                        </label>

                        <input type="hidden" name="parent_id" value="{{ parent_inode.id }}" required>

                        <input type="text" id="dirname" name="dirname"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="Example_dir_name_1" required />

                        <p class="mt-1 my-2 text-gray-500 dark:text-gray-300" id="file_input_help">Directory
                            name should not contain any special characters except _
                        </p>
                    </div>




                    <button type="Create Directory"
                        class="mt-1 w-full text-white bg-gray-900 hover:bg-blue-900  font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2">Create
                        Directory</button>
                </form>
            </div>
        </div>




        <h1 class="font-mono sm:text-3xl text-center text-2xl font-medium title-font mb-4 text-gray-900">All Files</h1>

        <nav class="flex justify-between" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                <li class="inline-flex items-center">
                    <a href="/all_files/{% if parent_inode.id == 1 %}{{ 1 }}{% else %}{{parent_inode.parent_id}}{% endif %}"
                        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
                        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor" viewBox="0 0 20 20">
                            <path
                                d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z" />
                        </svg>

                        {{parent_inode.name}}
                    </a>
                </li>
            </ol>
            <a href="/paste/{{parent_inode.id}}"
                class="flex flex-row items-center justify-center mx-2 border-2 border-slate-900 rounded hover:bg-blue-600 hover:text-white">
                <img class="basis-1/2 px-1 py-1" width="32" height="32" src="https://img.icons8.com/color/48/paste.png"
                    alt="paste" />
                <p class="basis-1/2 font-mono text-sm pr-2">
                    Paste
                </p>
            </a>
        </nav>






        <hr>
        <br><br><br>





        <div class="mx-auto mt-5 w-full flex flex-wrap items-center justify-center">

            {% for inode in inodes %}
            <div class="row">
                <div class="col">

                    <div class="w-44 mx-3 my-2 p-2 border rounded-xl border-slate-600">
                        <div class="flex flex-row justify-between">

                            {% if inode.is_file %}
                            <a href="/download/{{ inode.id }}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/material-rounded/24/download--v1.png"
                                    alt="download icon" />
                            </a>
                            {% endif %}

                            <a href="/delete/{{inode.id}}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/color/48/delete-sign--v1.png" alt="filled-trash" />
                            </a>

                            <a href="/copy/{{inode.id}}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/material-rounded/24/copy.png" alt="copy" />
                            </a>

                            <a href="/move/{{inode.id}}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/material-rounded/24/cut.png" alt="cut" />
                            </a>

                        </div>
                        <hr>
                        {% if inode.is_file %}
                        <div href="/all_files/{{inode.id}}" class="flex flex-col justify-center items-center">
                            {% else %}

                            <a href="/all_files/{{inode.id}}" class="flex flex-col justify-center items-center">
                                {% endif%}


                                {% if inode.is_file %}
                                <img class="rounded-t-xl" height="100" width="100"
                                    src="https://img.icons8.com/fluency/48/file.png" alt="File Icon">
                                {% else %}

                                <img class="rounded-t-xl" height="100" width="100"
                                    src="https://img.icons8.com/fluency/48/folder-invoices--v1.png"
                                    alt="Directory Icon">
                                {% endif %}

                                <h3 class="font-mono font-bold truncate w-full text-center">
                                    {{ inode.name }}
                                </h3>

                                {% if inode.is_file %}
                        </div>
                        {% else %}

                        </a>
                        {% endif%}
                    </div>





                </div>
            </div>



            {% endfor %}
        </div>
    </div>
</section>



{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FileXplore</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

</head>

<body>

    <!-- Navbar Start -->

    <header class="text-gray-400 bg-gray-900 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a href="{{ url_for('views.home') }}"
                class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
                <img width="48" height="48" src="https://img.icons8.com/fluency/48/windows-explorer.png"
                    alt="windows-explorer" />
                <span class="ml-3 text-xl">FileXplore</span>
            </a>
            <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
                <a href="{{ url_for('views.upload') }}" class="mr-5 hover:text-white">Upload</a>
            </nav>
            <button
                class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">Button
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
            </button>
        </div>
    </header>

    <!-- Navbar End -->




    {% with messages = get_flashed_messages() %}
    {% if messages %}

    {% for message in messages %}
    <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
        <span class="font-medium">{{ message }}
    </div>
    {% endfor %}

    {% endif %}
    {% endwith %}


    {% block content %}
    {% endblock %}



    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
</body>


</html>

app/templates/home.html
{% extends "base.html" %}


{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-5 mx-auto">

        <div class="flex flex-row grid grid-cols-2 gap-2 text-center w-full mb-20">

            <div class="border-2 border-slate-900 rounded-xl">

                <h3 class="font-mono">UPLOAD A FILE</h3>

                <div class="mx-auto w-full px-5 py-5">
                    <form method="post" action="/upload" enctype="multipart/form-data">


                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                            for="file_input">Select File</label>
                        <input
                            class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
                            name="file" aria-describedby="file_input_help" id="file_input" type="file" required>


                        <input type="hidden" name="parent_id" value="{{ parent_inode.id }}">

                        <p class="mt-1 mx-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">ALLOWED
                            EXTENSIONS : TXT,
                            PDF,
                            PNG, JPG, JPEG, GIF, MP4, DOCX, PPTX
                        </p>

                        <input type="submit" value="Upload File"
                            class="my-5 w-full text-white bg-gray-900 hover:bg-blue-900  font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2">

                    </form>
                </div>
            </div>




            <div class="border-2 border-slate-900 rounded-xl">

                <h3 class="font-mono">CREATE NEW DIRECTORY</h3>
                <form method="post" action="/create" class="my-5 container mx-auto w-full px-4">
                    <div class="mb-3">
                        <label for="dirname"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Directory
                            Name
                            :
                        </label>

                        <input type="hidden" name="parent_id" value="{{ parent_inode.id }}" required>

                        <input type="text" id="dirname" name="dirname"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="Example_dir_name_1" required />

                        <p class="mt-1 my-2 text-gray-500 dark:text-gray-300" id="file_input_help">Directory
                            name should not contain any special characters except _
                        </p>
                    </div>




                    <button type="Create Directory"
                        class="mt-1 w-full text-white bg-gray-900 hover:bg-blue-900  font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2">Create
                        Directory</button>
                </form>
            </div>
        </div>




        <h1 class="font-mono sm:text-3xl text-center text-2xl font-medium title-font mb-4 text-gray-900">All Files</h1>

        <nav class="flex justify-between" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                <li class="inline-flex items-center">
                    <a href="/all_files/{% if parent_inode.id == 1 %}{{ 1 }}{% else %}{{parent_inode.parent_id}}{% endif %}"
                        class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
                        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor" viewBox="0 0 20 20">
                            <path
                                d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z" />
                        </svg>

                        {{parent_inode.name}}
                    </a>
                </li>
            </ol>
            <a href="/paste/{{parent_inode.id}}"
                class="flex flex-row items-center justify-center mx-2 border-2 border-slate-900 rounded hover:bg-blue-600 hover:text-white">
                <img class="basis-1/2 px-1 py-1" width="32" height="32" src="https://img.icons8.com/color/48/paste.png"
                    alt="paste" />
                <p class="basis-1/2 font-mono text-sm pr-2">
                    Paste
                </p>
            </a>
        </nav>






        <hr>
        <br><br><br>





        <div class="mx-auto mt-5 w-full flex flex-wrap items-center justify-center">

            {% for inode in inodes %}
            <div class="row">
                <div class="col">

                    <div class="w-44 mx-3 my-2 p-2 border rounded-xl border-slate-600">
                        <div class="flex flex-row justify-between">

                            {% if inode.is_file %}
                            <a href="/download/{{ inode.id }}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/material-rounded/24/download--v1.png"
                                    alt="download icon" />
                            </a>
                            {% endif %}

                            <a href="/delete/{{inode.id}}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/color/48/delete-sign--v1.png" alt="filled-trash" />
                            </a>

                            <a href="/copy/{{inode.id}}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/material-rounded/24/copy.png" alt="copy" />
                            </a>

                            <a href="/move/{{inode.id}}">
                                <img width="24" height="24" class="my-2 mx-1 basis-1/4"
                                    src="https://img.icons8.com/material-rounded/24/cut.png" alt="cut" />
                            </a>

                        </div>
                        <hr>
                        {% if inode.is_file %}
                        <div href="/all_files/{{inode.id}}" class="flex flex-col justify-center items-center">
                            {% else %}

                            <a href="/all_files/{{inode.id}}" class="flex flex-col justify-center items-center">
                                {% endif%}


                                {% if inode.is_file %}
                                <img class="rounded-t-xl" height="100" width="100"
                                    src="https://img.icons8.com/fluency/48/file.png" alt="File Icon">
                                {% else %}

                                <img class="rounded-t-xl" height="100" width="100"
                                    src="https://img.icons8.com/fluency/48/folder-invoices--v1.png"
                                    alt="Directory Icon">
                                {% endif %}

                                <h3 class="font-mono font-bold truncate w-full text-center">
                                    {{ inode.name }}
                                </h3>

                                {% if inode.is_file %}
                        </div>
                        {% else %}

                        </a>
                        {% endif%}
                    </div>





                </div>
            </div>



            {% endfor %}
        </div>
    </div>
</section>



{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block content %}


<h3 class="font-mono">UPLOAD A FILE</h3>

<form method="post" enctype="multipart/form-data">

    <div class="container mx-auto w-1/2 px-4 my-5">

        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="file_input">Select File</label>
        <input
            class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
            name="file" aria-describedby="file_input_help" id="file_input" type="file">


        <input type="hidden" name="parent_id" value="1">

        <p class="mt-1 mx-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">ALLOWED EXTENSIONS : TXT,
            PDF,
            PNG, JPG, JPEG, GIF, MP4, DOCX, PPTX
        </p>

        <input type="submit" value="Upload File"
            class="my-5 w-full text-white bg-gray-900 hover:bg-blue-900  font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2">

    </div>
</form>







{% endblock %}